import stringSimilarity from "string-similarity";

export const intents =[
    {
        "intent": "who is obed",
        "examples": [
            "Who is Obed?",
            "Can you tell me about Obed?",
            "Who’s Obed?",
            "What’s Obed’s background?",
            "Tell me about this Obed person",
            "Who is this Obed guy?",
            "What does Obed do?",
            "Who is Obed in your organization?",
            "Tell me more about Obed",
            "Is Obed someone important?",
            "What’s Obed’s role?",
            "Who is the person named Obed?",
            "Give me details on Obed",
            "What can you say about Obed?",
            "Who’s the guy called Obed?",
            "What is Obed known for?",
            "Tell me something about Obed",
            "Who is Obed associated with?",
            "What’s the deal with Obed?",
            "Can you explain who Obed is?",
            "Who’s that Obed you mentioned?",
            "What’s Obed all about?",
            "Tell me who Obed is, please"
        ],
        "responses": ["Hi — he is a programmer"]
    },
    {
        "intent": "greeting",
        "examples": [
            "Hello",
            "Hi",
            "Hey there",
            "Good morning",
            "Hey, how’s it going?",
            "Hi there!",
            "Good afternoon",
            "Hello, how are you?",
            "Hey, what’s up?",
            "Good evening!",
            "Hiya!",
            "Greetings!",
            "What’s good?",
            "Hello there!",
            "Yo, how’s it hangin’?",
            "Hi, how’s everything?",
            "Good day!",
            "Hey, nice to see you!",
            "Morning!",
            "What’s new with you?",
            "Hello, what can you do?",
            "Hi, ready to chat?",
            "Hey, how can you help?"
        ],
        "responses": ["Hi — I’m the STEM Inspires assistant. I can help with programs, events, women in STEM, donations, and more."]
    },
    {
        "intent": "what_is_stem_inspires",
        "examples": [
            "What is STEM Inspires?",
            "Tell me about STEM Inspires",
            "Who are you?",
            "What’s STEM Inspires all about?",
            "Can you explain STEM Inspires?",
            "What does STEM Inspires do?",
            "Who is behind STEM Inspires?",
            "What’s the deal with STEM Inspires?",
            "Tell me more about your organization",
            "What is the STEM Inspires program?",
            "Who runs STEM Inspires?",
            "What’s the purpose of STEM Inspires?",
            "Can you describe STEM Inspires?",
            "What kind of organization is STEM Inspires?",
            "Tell me what STEM Inspires is",
            "What’s the mission of STEM Inspires?",
            "Who are the people at STEM Inspires?",
            "What does your group do?",
            "Explain what STEM Inspires is about",
            "What’s the story behind STEM Inspires?",
            "Give me details on STEM Inspires",
            "What makes STEM Inspires unique?"
        ],
        "responses": ["STEM Inspires is a nonprofit bringing robotics and STEM education to youth ages 9–16 through FIRST LEGO League."]
    },
    {
        "intent": "mission",
        "examples": [
            "What is your mission?",
            "What do you aim to do?",
            "What is your goal?",
            "What’s the mission of STEM Inspires?",
            "What are you trying to achieve?",
            "What’s your purpose?",
            "What goals does STEM Inspires have?",
            "What’s the main objective?",
            "What are you working toward?",
            "Tell me about your mission statement",
            "What’s your organization’s aim?",
            "What do you hope to accomplish?",
            "What’s the big plan for STEM Inspires?",
            "What drives your organization?",
            "What’s the core mission here?",
            "What are your primary goals?",
            "What’s the point of your work?",
            "What’s STEM Inspires’ focus?",
            "What do you want to achieve long-term?",
            "What’s your reason for existing?",
            "Tell me about your purpose",
            "What’s the vision behind your mission?"
        ],
        "responses": ["We inspire the next generation of innovators through inclusive, hands-on robotics programs."]
    },
    {
        "intent": "vision",
        "examples": [
            "What is your vision?",
            "Future goals?",
            "Where are you heading?",
            "What’s the future for STEM Inspires?",
            "What’s your long-term vision?",
            "Where do you see yourself in the future?",
            "What are your future plans?",
            "What’s the big picture for STEM Inspires?",
            "What’s your vision for the future?",
            "Where is STEM Inspires going?",
            "What are your aspirations?",
            "What’s the long-term goal?",
            "What do you envision for the future?",
            "What’s your dream for STEM Inspires?",
            "What’s the roadmap ahead?",
            "Where do you want to take this?",
            "What’s the future outlook?",
            "What are you planning for the long haul?",
            "What’s the endgame for STEM Inspires?",
            "What’s your vision statement?",
            "Where are you aiming to go?",
            "What’s next for your organization?"
        ],
        "responses": ["Our vision is to grow robotics across Africa and empower young engineers."]
    },
    {
        "intent": "fll_program",
        "examples": [
            "What is FIRST LEGO League?",
            "Explain FLL",
            "How does FLL work?",
            "What’s FIRST LEGO League about?",
            "Tell me about FLL",
            "What is the FLL program?",
            "How does FIRST LEGO League function?",
            "What’s the deal with FLL?",
            "Can you describe FIRST LEGO League?",
            "What happens in FLL?",
            "What’s the structure of FLL?",
            "How is FLL organized?",
            "What do kids do in FLL?",
            "Tell me more about FIRST LEGO League",
            "What’s the purpose of FLL?",
            "How does the FLL program operate?",
            "What’s involved in FIRST LEGO League?",
            "Explain the FLL competition",
            "What activities are in FLL?",
            "What’s the focus of FIRST LEGO League?",
            "How do students participate in FLL?",
            "What’s the format of FLL?"
        ],
        "responses": ["FLL introduces STEM to kids 9–16 through robotics, teamwork, and problem solving."]
    },
    {
        "intent": "age_group",
        "examples": [
            "Who can join?",
            "What ages are allowed?",
            "Age requirements?",
            "Who’s eligible to participate?",
            "What’s the age range for your programs?",
            "Can kids of any age join?",
            "What ages can join STEM Inspires?",
            "Who’s allowed to participate?",
            "What’s the age limit for FLL?",
            "Are there age restrictions?",
            "What ages are your programs for?",
            "Who can sign up for your activities?",
            "What’s the age group for robotics?",
            "Can teenagers join?",
            "What’s the minimum age to participate?",
            "Are there age rules for FLL?",
            "Who’s the target age group?",
            "What ages do you work with?",
            "Can younger kids join?",
            "What’s the age cutoff?",
            "Who qualifies age-wise?",
            "What’s the age eligibility?"
        ],
        "responses": ["The program is for youth ages 9–16."]
    },
    {
        "intent": "events",
        "examples": [
            "Tell me about your events",
            "What competitions do you host?",
            "National Championship?",
            "What events does STEM Inspires run?",
            "What’s your event lineup?",
            "What competitions are there?",
            "Tell me about your robotics events",
            "What’s the National Championship about?",
            "What kind of events do you organize?",
            "Are there any big events?",
            "What’s happening with your competitions?",
            "Tell me about the robotics championship",
            "What events do you put on?",
            "What’s the schedule for your events?",
            "What competitions do students join?",
            "What’s the deal with your events?",
            "Are there annual competitions?",
            "What’s the National Robotics Championship?",
            "What events can schools participate in?",
            "Tell me about your tournaments",
            "What’s the biggest event you host?",
            "What competitions are coming up?"
        ],
        "responses": ["We host the Annual National Robotics Championship of Rwanda and FLL competitions."]
    },
    {
        "intent": "bring_fll",
        "examples": [
            "How can I bring FLL to my school?",
            "Start a robotics team",
            "How do schools join?",
            "How can my school get involved with FLL?",
            "What’s the process to start FLL at school?",
            "How do I set up a robotics team?",
            "How can we join FIRST LEGO League?",
            "What steps do schools take to join FLL?",
            "How do I get FLL in my school?",
            "Can my school start a robotics program?",
            "How do we bring robotics to our school?",
            "What’s needed to join FLL?",
            "How can a school participate in FLL?",
            "How do I start an FLL team?",
            "What’s the way to get FLL at my school?",
            "How can we launch a robotics team?",
            "What do schools need for FLL?",
            "How do I introduce FLL to my school?",
            "Can schools join your robotics program?",
            "How do we get started with FLL?",
            "What’s the process for schools to join?",
            "How can my school start with robotics?"
        ],
        "responses": ["Use 'Get Started' on our site. A mentor will guide your school to join FLL."]
    },
    {
        "intent": "school_process",
        "examples": [
            "How do you recruit schools?",
            "School joining process?",
            "Steps to join?",
            "How do schools get involved?",
            "What’s the process for schools to join?",
            "How do you bring schools on board?",
            "What steps do schools follow to join?",
            "How are schools recruited for FLL?",
            "What’s the onboarding process for schools?",
            "How do schools sign up?",
            "What’s the procedure for schools?",
            "How do you get schools to participate?",
            "What’s the process to join your programs?",
            "How do schools become part of FLL?",
            "What do schools need to do to join?",
            "How do you engage schools?",
            "What’s the recruitment process for schools?",
            "How can a school join your program?",
            "What are the steps for school participation?",
            "How do you get schools started?",
            "What’s the school enrollment process?",
            "How do schools get on board with FLL?"
        ],
        "responses": ["We introduce FLL, address challenges, get schools started, and provide ongoing support."]
    },
    {
        "intent": "support_schools",
        "examples": [
            "How do you support schools?",
            "What help do schools get?",
            "Do you provide kits?",
            "What kind of support do schools receive?",
            "How do you assist schools in FLL?",
            "What resources do schools get?",
            "Do you give schools materials?",
            "How are schools supported in your program?",
            "What kind of help do you offer schools?",
            "Do schools get robotics kits?",
            "What support is available for schools?",
            "How do you help schools with robotics?",
            "Do you supply schools with equipment?",
            "What assistance do schools get?",
            "How do you support school teams?",
            "Do you provide tools for schools?",
            "What’s the support system for schools?",
            "How do schools get help from you?",
            "Do you donate resources to schools?",
            "What kind of aid do schools receive?",
            "How do you back schools in FLL?",
            "What materials do schools get?"
        ],
        "responses": ["We donate kits, train coaches, and mentor teams continuously."]
    },
    {
        "intent": "capacity_building",
        "examples": [
            "Do you train teachers?",
            "Workshops for coaches?",
            "Coach support?",
            "Do you offer teacher training?",
            "How do you support coaches?",
            "Are there workshops for teachers?",
            "Do you help train robotics coaches?",
            "What training do teachers get?",
            "How do you build coach skills?",
            "Are there programs for teacher training?",
            "Do you provide coach workshops?",
            "How do teachers learn to coach?",
            "What support do coaches receive?",
            "Do you run training for educators?",
            "How do you prepare teachers for FLL?",
            "Are there coaching classes?",
            "What kind of training for coaches?",
            "Do you help teachers with robotics?",
            "How do you train team coaches?",
            "Are workshops available for coaches?",
            "What’s the training process for teachers?",
            "Do you offer coach development?"
        ],
        "responses": ["Yes — we run workshops to build coaches’ skills and confidence."]
    },
    {
        "intent": "continuous_support",
        "examples": [
            "Do you guide teams?",
            "Do you keep helping?",
            "After starting, what next?",
            "How do you support teams ongoing?",
            "Do you provide continuous help?",
            "What happens after teams start?",
            "Do you mentor teams regularly?",
            "How do you keep supporting teams?",
            "Is there ongoing support for teams?",
            "What’s the follow-up support?",
            "Do you stay with teams after starting?",
            "How do teams get continuous help?",
            "What support do teams get long-term?",
            "Do you guide teams throughout?",
            "What’s the ongoing help for teams?",
            "How do you assist teams over time?",
            "Do you provide regular mentoring?",
            "What’s the support after joining?",
            "How do you help teams continuously?",
            "Do teams get ongoing guidance?",
            "What’s the long-term support plan?",
            "How do you keep helping teams?"
        ],
        "responses": ["We mentor teams weekly, share resources, and support learning."]
    },
    {
        "intent": "impact_numbers",
        "examples": [
            "How many teams?",
            "Impact so far?",
            "How many students?",
            "What’s your reach?",
            "How many schools are involved?",
            "What’s the impact of STEM Inspires?",
            "How many kids have you reached?",
            "What’s the number of teams?",
            "How many students participate?",
            "What’s your program’s impact?",
            "How many teams have you started?",
            "What’s the scale of your work?",
            "How many students are involved?",
            "What’s the total impact so far?",
            "How many schools have joined?",
            "What’s the reach of your programs?",
            "How many kids are in FLL?",
            "What’s the number of participants?",
            "How many teams compete?",
            "What’s the overall impact?",
            "How many students benefit?",
            "What’s your program’s reach?"
        ],
        "responses": ["We’ve launched multiple teams, reached many students, and hosted competitions."]
    },
    {
        "intent": "build_excitement",
        "examples": [
            "How do you build excitement?",
            "How do you motivate?",
            "Student engagement?",
            "How do you get students excited?",
            "What’s your approach to motivation?",
            "How do you engage kids?",
            "How do you inspire students?",
            "What gets kids excited about FLL?",
            "How do you make robotics fun?",
            "How do you motivate schools?",
            "What’s your strategy for engagement?",
            "How do you get kids interested?",
            "How do you build enthusiasm?",
            "What inspires students to join?",
            "How do you create excitement?",
            "How do you engage teachers?",
            "What’s your way of motivating kids?",
            "How do you get students pumped?",
            "How do you spark interest in FLL?",
            "What’s your engagement plan?",
            "How do you excite schools?",
            "What motivates your participants?"
        ],
        "responses": ["We visit schools, present FLL, and inspire teachers and students to join."]
    },
    {
        "intent": "build_resources",
        "examples": [
            "Do you provide materials?",
            "What resources do you give?",
            "Do you supply kits?",
            "What materials do schools get?",
            "Do you give robotics equipment?",
            "What resources are provided?",
            "Do schools get supplies?",
            "What kind of materials do you offer?",
            "Do you donate robotics kits?",
            "What tools do schools receive?",
            "Are resources provided to schools?",
            "What equipment do you supply?",
            "Do you give out kits for FLL?",
            "What’s included in your resources?",
            "Do schools get robotics materials?",
            "What supplies do you provide?",
            "Do you offer robotics tools?",
            "What resources do teams get?",
            "Do you donate equipment to schools?",
            "What materials support FLL?",
            "Are kits provided to schools?",
            "What do you give to teams?"
        ],
        "responses": ["We donate starter kits, expansion sets, and competition mats to schools."]
    },
    {
        "intent": "build_engineers",
        "examples": [
            "How do you build engineers?",
            "Student development?",
            "How do kids learn?",
            "How do you train future engineers?",
            "What’s your approach to student growth?",
            "How do students develop skills?",
            "How do you help kids become engineers?",
            "What’s the process for student learning?",
            "How do kids gain engineering skills?",
            "What helps students grow in STEM?",
            "How do you prepare kids for engineering?",
            "What’s your method for teaching kids?",
            "How do students learn robotics?",
            "What’s the learning path for kids?",
            "How do you develop young engineers?",
            "What skills do kids learn?",
            "How do you teach engineering?",
            "What’s the student development plan?",
            "How do kids build STEM skills?",
            "What’s the process for growing engineers?",
            "How do you support student learning?",
            "What helps kids become innovators?"
        ],
        "responses": ["We mentor, share online resources, and meet teams weekly to help them grow."]
    },
    {
        "intent": "women_in_stem",
        "examples": [
            "Do you support women?",
            "Girls in STEM?",
            "Women in robotics?",
            "How do you promote girls in STEM?",
            "Do you focus on women in STEM?",
            "Are girls involved in your programs?",
            "How do you support women in robotics?",
            "Do you encourage girls in STEM?",
            "What’s your work with women in STEM?",
            "How do girls participate in FLL?",
            "Do you promote female engineers?",
            "What do you do for girls in robotics?",
            "Are women a focus in your programs?",
            "How do you help girls in STEM?",
            "Do you support female students?",
            "What’s your approach to women in STEM?",
            "How do you involve girls in robotics?",
            "Do you work with women in engineering?",
            "What’s your role in girls’ STEM education?",
            "How do you empower women in STEM?",
            "Are girls a priority in your work?",
            "What do you do for female participants?"
        ],
        "responses": ["Yes — we are women-led and work with 500+ girls across all-girls schools."]
    },
    {
        "intent": "girls_schools",
        "examples": [
            "Which girls schools?",
            "Do you work with girls only schools?",
            "Women-founded programs?",
            "What girls’ schools do you partner with?",
            "Are you involved with all-girls schools?",
            "Which schools for girls do you work with?",
            "Do you collaborate with girls’ schools?",
            "What’s your work with girls-only schools?",
            "Which all-girls schools are involved?",
            "Do you partner with female schools?",
            "What girls’ schools are in your program?",
            "Are there specific girls’ schools you work with?",
            "Which schools for girls are part of FLL?",
            "Do you support girls-only education?",
            "What’s your partnership with girls’ schools?",
            "Which all-girls schools do you help?",
            "Are girls’ schools part of your work?",
            "What female schools do you collaborate with?",
            "Do you work with women-led schools?",
            "Which girls’ schools participate?",
            "What’s your role with girls’ schools?",
            "Are there girls-only schools in FLL?"
        ],
        "responses": ["We partner with Maranyundo Girls, FAWE, Gashora Girls Academy, and others."]
    },
    {
        "intent": "champions",
        "examples": [
            "Who are the champions?",
            "Which teams won?",
            "Top schools?",
            "Who won the robotics championship?",
            "What teams were victorious?",
            "Which schools are the best?",
            "Who are the top teams?",
            "What’s the winning team?",
            "Which schools won competitions?",
            "Who took the championship title?",
            "What teams came out on top?",
            "Which schools are champions?",
            "Who won in 2023?",
            "What are the top-performing schools?",
            "Which teams are the winners?",
            "Who’s leading in competitions?",
            "What schools won the robotics event?",
            "Who are the competition winners?",
            "Which teams excelled?",
            "What’s the top school in FLL?",
            "Who won the national championship?",
            "Which teams are the best in FLL?"
        ],
        "responses": ["Maranyundo Girls won the 2023 championship. FAWE and Gashora are top teams."]
    },
    {
        "intent": "donate",
        "examples": [
            "How can I donate?",
            "Donation options",
            "Support financially",
            "How do I give money?",
            "What’s the way to donate?",
            "Can I contribute financially?",
            "How can I support with a donation?",
            "What are the donation methods?",
            "How do I make a donation?",
            "Can I help with funding?",
            "What’s the process to donate?",
            "How can I give to STEM Inspires?",
            "Are there ways to donate money?",
            "How do I send a donation?",
            "What’s the donation procedure?",
            "Can I make a financial contribution?",
            "How do I support with money?",
            "What are my donation options?",
            "How can I fund your programs?",
            "What’s the way to contribute?",
            "How do I give to your cause?",
            "Can I donate to your organization?"
        ],
        "responses": ["Click 'Donate' on our site or email info@steminspires.tech. EIN: 92-0345640."]
    },
    {
        "intent": "sponsor_team",
        "examples": [
            "How do I sponsor a team?",
            "Sponsor students",
            "Help a robotics team",
            "How can I fund a team?",
            "What’s the way to sponsor a team?",
            "Can I support a robotics team?",
            "How do I back a student team?",
            "What’s the process to sponsor?",
            "How can I help a team financially?",
            "Can I sponsor kids in robotics?",
            "How do I support a team?",
            "What’s the sponsorship process?",
            "How can I fund students in FLL?",
            "Can I contribute to a team’s costs?",
            "How do I become a team sponsor?",
            "What’s the way to help a team?",
            "Can I support a school’s team?",
            "How do I sponsor a robotics group?",
            "What are the sponsorship options?",
            "How can I help fund a team?",
            "What’s the process for team sponsorship?",
            "Can I back a team in FLL?"
        ],
        "responses": ["You can sponsor a team through our 'Sponsor a Team' option on the website."]
    },
    {
        "intent": "fund_future",
        "examples": [
            "What is Fund Their Future?",
            "What is your fund program?",
            "Future funding?",
            "What’s the Fund Their Future campaign?",
            "Tell me about Fund Their Future",
            "What’s your funding program?",
            "What’s Fund Their Future about?",
            "Can you explain Fund Their Future?",
            "What’s the deal with Fund Their Future?",
            "What’s your future funding plan?",
            "What’s the purpose of Fund Their Future?",
            "How does Fund Their Future work?",
            "What’s the goal of your fund program?",
            "Tell me more about your funding campaign",
            "What’s the focus of Fund Their Future?",
            "What’s your program for future funding?",
            "Can you describe Fund Their Future?",
            "What’s the funding initiative about?",
            "What’s the Fund Their Future program?",
            "How do you fund the future?",
            "What’s the campaign for future support?",
            "What’s involved in Fund Their Future?"
        ],
        "responses": ["Fund Their Future is our campaign to support youth robotics and STEM education."]
    },
    {
        "intent": "get_involved",
        "examples": [
            "How do I get involved?",
            "Volunteer with you",
            "Join your work",
            "How can I participate?",
            "What’s the way to get involved?",
            "Can I help with your programs?",
            "How do I join STEM Inspires?",
            "What can I do to get involved?",
            "How can I contribute to your work?",
            "Can I volunteer with STEM Inspires?",
            "How do I become part of your team?",
            "What’s the process to join in?",
            "How can I support your mission?",
            "Can I get involved with FLL?",
            "What’s the way to participate?",
            "How do I help your organization?",
            "Can I join your efforts?",
            "What opportunities are there to help?",
            "How can I be part of STEM Inspires?",
            "What’s the way to volunteer?",
            "How do I engage with your programs?",
            "Can I work with you?"
        ],
        "responses": ["Visit 'Get Involved' on our site — you can volunteer, partner, or mentor."]
    },
    {
        "intent": "volunteer",
        "examples": [
            "Can I volunteer?",
            "How do I help?",
            "Join as volunteer",
            "How can I volunteer with you?",
            "What’s the way to volunteer?",
            "Can I help out as a volunteer?",
            "How do I become a volunteer?",
            "What volunteer opportunities are there?",
            "Can I assist as a volunteer?",
            "How do I sign up to volunteer?",
            "What’s the process to help out?",
            "Can I contribute as a volunteer?",
            "How can I volunteer for FLL?",
            "What can I do as a volunteer?",
            "How do I get started volunteering?",
            "Are there volunteer roles available?",
            "How can I help as a volunteer?",
            "What’s the way to assist?",
            "Can I volunteer with STEM Inspires?",
            "How do I join as a volunteer?",
            "What volunteer positions do you have?",
            "How can I support as a volunteer?"
        ],
        "responses": ["Yes — check 'Get Involved' on our site for volunteer opportunities."]
    },
    {
        "intent": "partnerships",
        "examples": [
            "Do you partner with schools?",
            "Partnerships?",
            "Work with other orgs?",
            "Do you collaborate with schools?",
            "What partnerships do you have?",
            "Do you work with other organizations?",
            "How do you partner with schools?",
            "Are there partnerships with groups?",
            "Do you team up with schools?",
            "What’s your partnership model?",
            "Do you collaborate with nonprofits?",
            "How do you work with other orgs?",
            "Are schools your partners?",
            "What kind of partnerships do you form?",
            "Do you have school collaborations?",
            "How do you engage with partners?",
            "Do you partner with other groups?",
            "What’s your approach to partnerships?",
            "Do you work with educational orgs?",
            "How do schools partner with you?",
            "Are there collaboration opportunities?",
            "What partnerships support your work?"
        ],
        "responses": ["We partner with schools, teachers, and mentors to support robotics."]
    },
    {
        "intent": "contact",
        "examples": [
            "How can I contact you?",
            "Email address?",
            "Reach out to STEM Inspires",
            "What’s your contact info?",
            "How do I get in touch?",
            "Can you give me your email?",
            "How do I reach STEM Inspires?",
            "What’s the best way to contact you?",
            "How can I connect with you?",
            "What’s your contact email?",
            "How do I get ahold of you?",
            "Can I email you?",
            "What’s the email for STEM Inspires?",
            "How do I reach out to you?",
            "What’s your support email?",
            "How can I contact your team?",
            "What’s the way to get in touch?",
            "Can you share your contact details?",
            "How do I communicate with you?",
            "What’s the email to reach you?",
            "How can I send you a message?",
            "What’s your contact method?"
        ],
        "responses": ["Email info@steminspires.tech for donations, questions, or partnerships."]
    },
    {
        "intent": "ein_info",
        "examples": [
            "Are you registered?",
            "What is your EIN?",
            "Are you tax-exempt?",
            "Is STEM Inspires a nonprofit?",
            "What’s your tax ID?",
            "Are you a 501(c)(3)?",
            "What’s your EIN number?",
            "Is your organization registered?",
            "Do you have tax-exempt status?",
            "What’s the EIN for STEM Inspires?",
            "Are you a registered charity?",
            "What’s your nonprofit ID?",
            "Is STEM Inspires tax-exempt?",
            "What’s your organization’s EIN?",
            "Are you officially registered?",
            "Do you have a tax ID number?",
            "Is your group a 501(c)(3)?",
            "What’s the tax ID for donations?",
            "Are you a certified nonprofit?",
            "What’s your charity registration?",
            "Do you have an EIN for donations?",
            "Is STEM Inspires a registered 501(c)(3)?"
        ],
        "responses": ["Yes — we are a 501(c)(3) tax-exempt nonprofit. EIN: 92-0345640."]
    },
    {
        "intent": "location",
        "examples": [
            "Where are you based?",
            "Your location?",
            "Which country?",
            "Where is STEM Inspires located?",
            "What’s your base country?",
            "Where do you operate from?",
            "What’s your headquarters location?",
            "Where are you situated?",
            "In which country are you based?",
            "Where’s your main office?",
            "What’s the location of STEM Inspires?",
            "Where do you run your programs?",
            "What country do you work in?",
            "Where is your organization based?",
            "What’s your primary location?",
            "Where are you located geographically?",
            "What’s the base for STEM Inspires?",
            "Where do you conduct your work?",
            "In what region are you based?",
            "Where’s your operational base?",
            "What’s your home country?",
            "Where is your group located?"
        ],
        "responses": ["We are based in Rwanda and expanding across central Africa."]
    },
    {
        "intent": "robotics_focus",
        "examples": [
            "What do students learn?",
            "What do you teach?",
            "Focus of training?",
            "What skills do kids learn?",
            "What’s the focus of your programs?",
            "What do you teach students?",
            "What’s the training emphasis?",
            "What do participants learn?",
            "What skills are taught in FLL?",
            "What’s the core of your teaching?",
            "What do kids study in your programs?",
            "What’s the main focus of robotics?",
            "What do students gain from FLL?",
            "What’s taught in your programs?",
            "What skills do you focus on?",
            "What do kids learn in robotics?",
            "What’s the training about?",
            "What do you teach in FLL?",
            "What’s the learning focus?",
            "What skills do students develop?",
            "What’s the core training area?",
            "What do kids get out of your program?"
        ],
        "responses": ["We teach robot design, programming, teamwork, and problem solving."]
    },
    {
        "intent": "student_benefits",
        "examples": [
            "Why should kids join?",
            "Benefits for students?",
            "What do they gain?",
            "What do kids get from FLL?",
            "Why join your programs?",
            "What’s the value for students?",
            "What do students benefit from?",
            "Why should students participate?",
            "What’s in it for kids?",
            "What do kids gain from robotics?",
            "Why is FLL good for students?",
            "What are the perks for kids?",
            "What do students learn from joining?",
            "Why should kids get involved?",
            "What benefits do participants get?",
            "What’s the advantage for students?",
            "What do kids take away from FLL?",
            "Why is your program good for kids?",
            "What’s the benefit of joining?",
            "What do students achieve in FLL?",
            "Why should kids sign up?",
            "What’s the value of your programs?"
        ],
        "responses": ["They learn STEM, teamwork, leadership, and real-world problem solving."]
    },
    {
        "intent": "teacher_role",
        "examples": [
            "What about teachers?",
            "Do you train teachers?",
            "Role of coaches?",
            "What do teachers do in FLL?",
            "How are teachers involved?",
            "Do you support teachers?",
            "What’s the role of teachers?",
            "How do coaches participate?",
            "Do teachers get training?",
            "What do coaches do in your program?",
            "How do you involve teachers?",
            "What’s the teacher’s job in FLL?",
            "Do you prepare teachers for robotics?",
            "What role do educators play?",
            "How do teachers help teams?",
            "What’s the coach’s responsibility?",
            "Do you train educators?",
            "How are teachers supported?",
            "What do teachers contribute?",
            "What’s the role of coaches in FLL?",
            "How do educators get involved?",
            "What do teachers do in robotics?"
        ],
        "responses": ["We train and support teachers to coach robotics teams effectively."]
    },
    {
        "intent": "competition_format",
        "examples": [
            "How are competitions run?",
            "Competition format?",
            "How do matches work?",
            "What’s the structure of competitions?",
            "How do FLL competitions work?",
            "What’s the format of your events?",
            "How are robotics matches organized?",
            "What’s the competition setup?",
            "How do teams compete in FLL?",
            "What’s the process for competitions?",
            "How are your events structured?",
            "What’s the competition style?",
            "How do matches play out?",
            "What’s the format of robotics events?",
            "How do you run competitions?",
            "What’s the structure of FLL matches?",
            "How are tournaments organized?",
            "What’s the competition process?",
            "How do teams participate in events?",
            "What’s the setup for competitions?",
            "How do FLL tournaments work?",
            "What’s the event format?"
        ],
        "responses": ["Teams compete by designing, programming, and presenting robot solutions."]
    },
    {
        "intent": "africa_expansion",
        "examples": [
            "Do you work outside Rwanda?",
            "Do you expand?",
            "Where else are you?",
            "Are you in other countries?",
            "Do you operate beyond Rwanda?",
            "What’s your expansion plan?",
            "Are you growing outside Rwanda?",
            "Where else do you work?",
            "Do you have programs in other countries?",
            "Are you expanding in Africa?",
            "What’s your reach beyond Rwanda?",
            "Do you work in other African nations?",
            "Are you in central Africa?",
            "What’s your plan for growth?",
            "Do you operate in other regions?",
            "Are you expanding FLL elsewhere?",
            "Where are you growing next?",
            "Do you have programs outside Rwanda?",
            "What’s your expansion strategy?",
            "Are you in other parts of Africa?",
            "Where else is STEM Inspires active?",
            "Do you plan to grow regionally?"
        ],
        "responses": ["Yes — we are expanding FLL across central Africa."]
    },
    {
        "intent": "student_stories",
        "examples": [
            "Any success stories?",
            "Student impact?",
            "Examples of achievements?",
            "What are some student successes?",
            "Do you have student stories?",
            "What’s the impact on students?",
            "Can you share success examples?",
            "What achievements have students made?",
            "Any notable student stories?",
            "What’s the impact of your programs?",
            "Do students have big wins?",
            "What are some student accomplishments?",
            "Can you tell me about student successes?",
            "What’s the effect on kids?",
            "Any examples of student achievements?",
            "What success stories do you have?",
            "How have students benefited?",
            "What are some team successes?",
            "Do you have stories of student impact?",
            "What’s the outcome for students?",
            "Any standout student stories?",
            "What have students achieved?"
        ],
        "responses": ["Our teams reach national levels, with champions like Maranyundo Girls."]
    },
    {
        "intent": "mentoring",
        "examples": [
            "Do you mentor students?",
            "Who mentors teams?",
            "Do they get guidance?",
            "How do you mentor kids?",
            "Who guides the teams?",
            "Do students get mentors?",
            "What’s your mentoring process?",
            "How are students mentored?",
            "Who helps the teams?",
            "Do you provide student guidance?",
            "What’s the role of mentors?",
            "How do mentors support teams?",
            "Do kids get mentoring?",
            "Who works with the students?",
            "What’s the mentoring approach?",
            "Do teams have mentors?",
            "How do you guide participants?",
            "Who provides team guidance?",
            "Do you offer student mentoring?",
            "What’s the support for teams?",
            "How are mentors involved?",
            "Do students get regular guidance?"
        ],
        "responses": ["Yes — our mentors guide students in robotics and teamwork."]
    },
    {
        "intent": "kits",
        "examples": [
            "What kits do you use?",
            "Do you use LEGO?",
            "Robotics kits?",
            "What equipment do you use?",
            "Are LEGO kits part of FLL?",
            "What robotics tools do you provide?",
            "What kind of kits are used?",
            "Do you use LEGO Education kits?",
            "What materials are in your kits?",
            "What robotics kits do teams get?",
            "Are your kits LEGO-based?",
            "What equipment is used in FLL?",
            "What’s in the robotics kits?",
            "Do you provide LEGO kits?",
            "What tools do teams use?",
            "What’s the kit for robotics?",
            "Do you use specific robotics kits?",
            "What materials do teams work with?",
            "Are LEGO sets part of your program?",
            "What kind of kits do you supply?",
            "What’s included in your robotics kits?",
            "Do teams get LEGO equipment?"
        ],
        "responses": ["We use LEGO Education kits, expansion sets, and competition mats."]
    },
    {
        "intent": "program_cost",
        "examples": [
            "Is there a cost?",
            "Do schools pay?",
            "Program fees?",
            "Is your program free?",
            "What’s the cost for schools?",
            "Are there fees for FLL?",
            "Do schools need to pay?",
            "What’s the price of the program?",
            "Is there a cost to join?",
            "Do you charge schools?",
            "What’s the fee for participation?",
            "Is FLL free for schools?",
            "Are there program costs?",
            "Do schools have to pay fees?",
            "What’s the cost to join FLL?",
            "Is there a fee for schools?",
            "Do you charge for resources?",
            "What’s the price for teams?",
            "Is the program free for schools?",
            "Are there costs for joining?",
            "Do schools pay for kits?",
            "What’s the financial commitment?"
        ],
        "responses": ["Schools in need get free kits and resources through our support."]
    },
    {
        "intent": "annual_event",
        "examples": [
            "What is your biggest event?",
            "Annual events?",
            "Robotics festival?",
            "What’s your main event?",
            "Do you have yearly events?",
            "What’s the big robotics event?",
            "What’s your annual competition?",
            "What’s the biggest robotics event?",
            "Do you host a yearly festival?",
            "What’s the main annual event?",
            "What’s your biggest tournament?",
            "Do you have an annual championship?",
            "What’s the top event you run?",
            "What’s the annual robotics event?",
            "Do you organize yearly competitions?",
            "What’s the biggest event of the year?",
            "What’s your main robotics festival?",
            "What’s the annual event for FLL?",
            "Do you have a major yearly event?",
            "What’s the top robotics competition?",
            "What’s your biggest annual gathering?",
            "What’s the main event each year?"
        ],
        "responses": ["The biggest event is the National Robotics Championship of Rwanda."]
    },
    {
        "intent": "who_runs",
        "examples": [
            "Who runs STEM Inspires?",
            "Leadership?",
            "Who is behind it?",
            "Who’s in charge of STEM Inspires?",
            "Who leads your organization?",
            "Who’s running the show?",
            "Who founded STEM Inspires?",
            "Who’s behind your programs?",
            "Who manages STEM Inspires?",
            "Who’s the leadership team?",
            "Who started your organization?",
            "Who’s at the helm of STEM Inspires?",
            "Who runs your nonprofit?",
            "Who’s the team behind STEM Inspires?",
            "Who leads your programs?",
            "Who’s in charge of your work?",
            "Who founded your group?",
            "Who’s leading STEM Inspires?",
            "Who runs the organization?",
            "Who’s behind the scenes?",
            "Who’s the head of STEM Inspires?",
            "Who manages your initiatives?"
        ],
        "responses": ["We are a women-founded and women-led organization."]
    },
    {
        "intent": "nonprofit_status",
        "examples": [
            "Are you nonprofit?",
            "Charity status?",
            "Are you 501c3?",
            "Is STEM Inspires a charity?",
            "Are you a registered nonprofit?",
            "What’s your nonprofit status?",
            "Do you have 501(c)(3) status?",
            "Is your organization a nonprofit?",
            "Are you a charitable organization?",
            "What’s your charity status?",
            "Is STEM Inspires a 501(c)(3)?",
            "Are you officially a nonprofit?",
            "Do you have nonprofit registration?",
            "Is your group a charity?",
            "What’s the status of your organization?",
            "Are you a tax-exempt nonprofit?",
            "Is STEM Inspires a registered charity?",
            "Do you have 501(c)(3) certification?",
            "Are you a nonprofit entity?",
            "What’s your organization’s status?",
            "Is your group tax-exempt?",
            "Are you a recognized nonprofit?"
        ],
        "responses": ["Yes — STEM Inspires is a registered 501(c)(3) nonprofit."]
    },
    {
        "intent": "how_to_apply",
        "examples": [
            "How do schools apply?",
            "Join program?",
            "Apply to participate?",
            "What’s the application process?",
            "How can schools sign up?",
            "How do schools join your program?",
            "What’s the process to apply?",
            "How do schools get started?",
            "What’s the way for schools to apply?",
            "How can a school join FLL?",
            "What steps do schools take to apply?",
            "How do schools enroll?",
            "What’s the application for schools?",
            "How can schools participate?",
            "What’s the process for joining?",
            "How do schools apply for FLL?",
            "What’s the sign-up process?",
            "How can a school get involved?",
            "What’s the way to join your program?",
            "How do schools register?",
            "What’s the application procedure?",
            "How can schools start with FLL?"
        ],
        "responses": ["Schools can apply through the 'Get Started' page on our site."]
    },
    {
        "intent": "email",
        "examples": [
            "What is your email?",
            "Contact email?",
            "Support email?",
            "What’s the email for STEM Inspires?",
            "Can you share your email address?",
            "What’s your support email?",
            "How do I email you?",
            "What’s the contact email address?",
            "What email should I use?",
            "Can I get your email?",
            "What’s the email to contact you?",
            "What’s your official email?",
            "How can I email STEM Inspires?",
            "What’s the email for support?",
            "Can you give me your contact email?",
            "What’s the email to reach you?",
            "What’s your team’s email?",
            "How do I send an email to you?",
            "What’s the email for inquiries?",
            "Can you share your support email?",
            "What’s the email address for contact?",
            "What’s the best email to use?"
        ],
        "responses": ["You can reach us at info@steminspires.tech."]
    },
    {
        "intent": "national_reach",
        "examples": [
            "Do you work nationally?",
            "Are you across Rwanda?",
            "Which schools?",
            "Do you operate nationwide?",
            "Are you active across Rwanda?",
            "What schools do you work with?",
            "Is your program national?",
            "Do you cover all of Rwanda?",
            "Which schools are involved?",
            "Are you nationwide in Rwanda?",
            "What’s your reach in Rwanda?",
            "Do you work with schools across Rwanda?",
            "Is your program country-wide?",
            "Which schools participate nationally?",
            "Do you have a national presence?",
            "What’s your coverage in Rwanda?",
            "Are schools from all over Rwanda involved?",
            "Do you engage schools nationwide?",
            "What’s your national scope?",
            "Are you active in all regions of Rwanda?",
            "Which schools are part of your program?",
            "Do you work with schools country-wide?"
        ],
        "responses": ["Yes — we work with schools nationwide to expand robotics."]
    },
    {
        "intent": "student_waiting",
        "examples": [
            "Why are students waiting?",
            "Why needed?",
            "Why demand?",
            "Why do students need your program?",
            "What’s the demand for your work?",
            "Why are kids waiting for robotics?",
            "What’s the need for STEM Inspires?",
            "Why is there a demand for FLL?",
            "Why do students want your program?",
            "What’s causing the wait for students?",
            "Why is your program needed?",
            "What’s the demand for robotics?",
            "Why are students eager to join?",
            "What’s the need for your work?",
            "Why do kids need robotics programs?",
            "What’s the reason for student demand?",
            "Why are students waiting for FLL?",
            "What’s driving the need for your program?",
            "Why is there a wait for your programs?",
            "Why do students need STEM Inspires?",
            "What’s the demand for your initiatives?",
            "Why are kids waiting to participate?"
        ],
        "responses": ["Many schools lacked resources or access until STEM Inspires stepped in."]
    },
    {
        "intent": "why_robots",
        "examples": [
            "Why robotics?",
            "Why focus on robots?",
            "Why not other STEM?",
            "Why choose robotics for kids?",
            "What’s the focus on robotics?",
            "Why do you teach robotics?",
            "Why not other STEM fields?",
            "What’s special about robotics?",
            "Why is robotics your focus?",
            "Why do you prioritize robots?",
            "What’s the reason for robotics?",
            "Why robotics over other STEM areas?",
            "What makes robotics important?",
            "Why focus on robotics programs?",
            "Why do kids learn robotics?",
            "What’s the value of robotics?",
            "Why not focus on other sciences?",
            "Why is robotics the main focus?",
            "What’s the benefit of robotics?",
            "Why choose robots for STEM?",
            "Why do you emphasize robotics?",
            "What’s the point of robotics?"
        ],
        "responses": ["Robotics teaches STEM, creativity, and teamwork in a fun way."]
    },
    {
        "intent": "future_students",
        "examples": [
            "What’s next for students?",
            "Future opportunities?",
            "Next steps?",
            "What’s the future for FLL students?",
            "What opportunities await students?",
            "What’s next after your program?",
            "What can students do next?",
            "What’s the path for students?",
            "What opportunities do kids get?",
            "What’s the next step for participants?",
            "What’s in store for students?",
            "What future paths do students have?",
            "What’s the next phase for kids?",
            "What opportunities follow FLL?",
            "What’s the future for participants?",
            "What can students pursue after?",
            "What’s the next stage for students?",
            "What opportunities are there post-FLL?",
            "What’s the future for your students?",
            "What’s next for kids in robotics?",
            "What paths open for students?",
            "What’s the future after your program?"
        ],
        "responses": ["We prepare students for engineering, innovation, and global opportunities."]
    },
    {
        "intent": "recognition",
        "examples": [
            "Any recognition?",
            "What do experts say?",
            "Who supports you?",
            "Have you received any awards?",
            "What’s the feedback on your work?",
            "Who recognizes your programs?",
            "Do experts praise your work?",
            "What’s the reputation of STEM Inspires?",
            "Have you been acknowledged?",
            "Who supports your initiatives?",
            "What do leaders say about you?",
            "Any notable recognition?",
            "What’s the expert opinion on you?",
            "Who endorses STEM Inspires?",
            "Have you gotten any praise?",
            "What’s the feedback from experts?",
            "Do you have any accolades?",
            "Who’s backing your programs?",
            "What’s the recognition for your work?",
            "Have you been honored?",
            "What do professionals say about you?",
            "Any awards or support for you?"
        ],
        "responses": ["Leaders like Olajide Ade Ajayi of Coderina praise our students’ dedication."]
    }
];

export const findBestIntentAdvanced = (input) => {
  const normalizedInput = input.toLowerCase();
  let bestMatch = null;
  let highestScore = 0;

  intents.forEach((intent) => {
    const examples = intent.examples.map((e) => e.toLowerCase());
    const match = stringSimilarity.findBestMatch(normalizedInput, examples);
    if (match.bestMatch.rating > highestScore) {
      highestScore = match.bestMatch.rating;
      bestMatch = intent;
    }
  });

  return highestScore > 0.3 ? bestMatch : null;
};
